### ISSUE TITLE
Incompatible with Python>=3.10 (AttributeError: module 'collections' has no attribute 'Mapping')

### ISSUE THREAD

**Issue by BlockDweller** [slezica/python-frozendict#39]
**Issue: error thrown on module import**
```
>>> import frozendict
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/crypt0xyc/projects/starknet-arb/.venv/lib/python3.10/site-packages/frozendict/__init__.py", line 16, in <module>
    class frozendict(collections.Mapping):
AttributeError: module 'collections' has no attribute 'Mapping'
```

**Proposed solution for Python 3.10 compatibility**
replace `collections.Mapping` with `collections.abc.Mapping`

**Comment by Marco-Sulla** [comment]
Hello @crypt0xyc . Project has moved here: https://github.com/Marco-Sulla/python-frozendict
